import erpnext.accounts.doctype.budget.budget as budget_module
from budget_control.override.budget import validate_expense_against_budget as custom_validate_budget_records

budget_module.validate_expense_against_budget = custom_validate_budget_records
